### ISSUE TITLE
develop ブランチを作成する

### ISSUE THREAD

**Issue by iQeda** [taichi-kobaya/LaravelPortfolio#2]
- develop ブランチで作業する
- main ブランチに PR を出す

これを徹底しましょう

**Comment by taichi-kobaya** [comment]
develop ブランチ作成しました！
develop ブランチからmainブランチにPull Requestsを出そうとすると
There isn’t anything to compare.
main and develop are identical.
と出て来ます。
そこからどうすればいいのか分かりません。
よろしくお願いします。

**Comment by iQeda** [comment]
英語をそのまま日本語に訳した通りですー
main と develop にコードの差分がないので PR 出す意味がないってことですね
このあと develop で作業すると思うので、そのあとに PR 出していただければ

**Comment by taichi-kobaya** [comment]
承知しました！ではこのまま作業を進めた後、PR出します

**Comment by taichi-kobaya** [comment]
対応したのでクローズします
