### ISSUE TITLE
まずルーティングを定義する

### ISSUE THREAD

**Issue by iQeda** [taichi-kobaya/LaravelPortfolio#3]
- https://github.com/taichi-kobaya/LaravelPortfolio/blob/main/routes/web.php

**Comment by taichi-kobaya** [comment]
PR出しました。
対応しましたのでクローズします。

**Comment by iQeda** [comment]
@taichi-kobaya 
PR 作成ありがとうございます！
https://github.com/taichi-kobaya/LaravelPortfolio/pull/11
↑ PR コメント書いたので見ておいてください〜
