### ISSUE TITLE
コントローラを作成する

### ISSUE THREAD

**Issue by iQeda** [taichi-kobaya/LaravelPortfolio#4]
ルーティングからいきなり View を呼び出すこともできますが、基本に忠実にコントローラから View を呼び出してください

**Comment by taichi-kobaya** [comment]
入力フォームからDBに挿入の流れ

ビューの雛形の作成～コントローラの作成（php artisan make:controller InsertDemoControllerコマンド実行→app/Http/Controllers/InsertDemoController.phpのコード更新）

の流れに沿ってやりました。

動作確認で
入力画面が表示できれば OKとありますが、ポートフォリオの場合どんな状態になっていればOKですか？

それからlocalhostでポートフォリオを表示するとCSSが機能していないようです。
今の段階では問題ないんでしょうか？

**Comment by iQeda** [comment]
> php artisan make:controller InsertDemoController
> app/Http/Controllers/InsertDemoController.phpのコード更新

まず `InsertDemoController.php` というコントローラ名が適切か考えてください。
「Laravel 学習帳で試しに Insert してみるデモ機能」を作ろうとしたので `InsertDemo` というコントローラ名になったに過ぎません。
今回は Portfolio トップページを表示するコントローラ・お問い合わせ内容を表示する管理者画面を表示するコントローラ 2 つあれば十分な認識です。

> ポートフォリオの場合どんな状態になっていればOK

ルーティングからそのコントローラを呼び出しておらず、
コントローラのメソッドに何も処理を書いていないのであれば何も変化はないはずです。

> ポートフォリオを表示するとCSSが機能していないようです。

`link` タグで正しく css ファイルを読み込んでいないからです。これは Blade 文法に沿ってください。
#6 の時点で対応すれば大丈夫です。

**Comment by taichi-kobaya** [comment]
そうするとInsertDemoController.phpでは不適切ですね。
もう一度よく考えてみます。

他2件の質問のご回答、承知しました。
ありがとうございます。

**Comment by taichi-kobaya** [comment]
Portfolio トップページを表示するコントローラ → TopPageController
お問い合わせ内容を表示する管理者画面を表示するコントローラ → AdministratorScreenController
ではどうでしょうか。

それから手順が前後してしまい申し訳ないのですが、

リクエストフォームの作成
docker-compose exec workspace bash

# InsertDemoRequest.php を作成する
php artisan make:request InsertDemoRequest
app/Http/Requests/InsertDemoRequest.php

↑リクエストフォームがどの画面を指しているのか分かりません。

入力フォーム＝名前やメールアドレス、性別等を入力するフォーム
確認画面＝入力フォームに入力した内容で良いか確認する為の画面

"リクエストフォームとはこれの事"というものがイメージできませんでしたので教えて頂ければ幸いです。

**Comment by iQeda** [comment]
> Portfolio トップページを表示するコントローラ → TopPageController

問題はなさそうです！

> お問い合わせ内容を表示する管理者画面を表示するコントローラ → AdministratorScreenController

Top「Page」があるなら、Administrator「Page」Controller が適切ではないでしょうか。
コントローラ名が長いので、僕なら `TopController`  / `AdminTopController` にするかもです。
※ 管理者画面は今後機能が増える可能性があるので「Top」と付けています

**Comment by iQeda** [comment]
リクエストフォームのクラスはまさに「リクエスト」を管理します。
今回だとユーザのお問い合わせ内容が格納されるはずです。
リクエストフォームを使って、お問い合わせ内容のバリデーションをしてあげてください。
内容的に問題なければ (モデルクラスを使って) データベースに保存、です。

**Comment by taichi-kobaya** [comment]
なるほどです！ありがとうございます。
確かにコントローラ名、こんなに長くてもいいのかなと思ってました。
TopController / AdminTopControllerでいきたいと思います！

**Comment by taichi-kobaya** [comment]
artisanコマンドでTopController / AdminTopControllerを作成しました。
それぞれのコントローラの中身のコードをどうすればいいのか分かりません。

app-LaravelTutorialEasy/app/Http/Controllers/InsertDemoController.phpのコードを参照してみましたが、
ここから進めずにいますので何かヒントを頂ければ幸いです。

**Comment by iQeda** [comment]
まず単純に Blade ファイルを表示してみてはいかがでしょうか。ルーティング→コントローラ→ビューの流れは押さえておいでください。現在、ルーティングから直接ビューを呼び出していますが例外的なやり方なので今は控えましょう(研修でやってません！)。つまりルーティングも修正対象です。

Admin の方はそもそも表示するお問い合わせデータがまだないので後回しでいいと思います。

**Comment by iQeda** [comment]
定期的にコミットをプッシュしてもらえると、コードレビューができるのでよろしくお願いします〜

**Comment by taichi-kobaya** [comment]
ルーティング→コントローラ→ビューの流れ、

web.php

Route::get('/taichihome', 'TopController@allUsers');

------------------------------------------------------------
app\Http\Controllers\TopController.php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class TopController extends Controller
{
    public function allUsers()
   {
       return view("taichihome/index");
   }
}
------------------------------------------------------------
このように修正しました！
コミットはプッシュ済みです。
よろしくお願いします。

**Comment by iQeda** [comment]
github にコードをコメントするときは Markdown が使えますので、
boostnote と同じようにシンタックスハイライトを使ってみてくださいー

**Comment by iQeda** [comment]
PR にコメントしました〜

**Comment by taichi-kobaya** [comment]
対応したのでクローズします。
