### ISSUE TITLE
taichihome をリネームする

### ISSUE THREAD

**Issue by iQeda** [taichi-kobaya/LaravelPortfolio#5]
小林さん専用のポートフォリオプロジェクトであることは自明なのに、わざわざ `LaravelPortfolio/resources/views/taichihome/`というディレクトリ名にする必要はないと思います。リネームしましょう。

**Comment by taichi-kobaya** [comment]
taichihome→homeにリネームし、ルーティング、コントローラ内のコードも修正しました。

**Comment by iQeda** [comment]
PR にコメントしました〜

**Comment by taichi-kobaya** [comment]
対応したのでクローズします。
