### ISSUE TITLE
マイグレーションファイルを作成する

### ISSUE THREAD

**Issue by iQeda** [taichi-kobaya/LaravelPortfolio#7]
お問い合わせ内容を保存する、ということはデータベースにテーブルが必要です。

1. テーブル設計する
2. マイグレーションファイルを作成する
3. マイグレーション実行する

上記対応を行ってください

**Comment by taichi-kobaya** [comment]
https://laraweb.net/knowledge/2232/
上記URLを参考に、以下手順でマイグレーション実行しました。
- php artisan make:migration create_contact_table コマンド実行
- database/migrations/2021_03_25_014659_create_contact_table.php  upメソッド編集
- php artisan migrate コマンド実行

**Comment by taichi-kobaya** [comment]
#8 モデルを作成する　にあたり、モデル名はテーブル名の単数形にする必要がある、とありましたので
テーブル名をcontactからcontactsに変更しました。

**Comment by taichi-kobaya** [comment]
↑すみません、下記youtube動画を参考にしました。
https://www.youtube.com/watch?v=DzsYsgRuwZE&t=10s
4:15～

**Comment by iQeda** [comment]
PR にコメントしました！
マイグレーションファイル名を変更すると、別ファイルとして扱われるのでマイグレーションコマンドが再度実行できてしまいますのでご注意を。(同じテーブルは作成できないので SQL エラーになるだけですが)
