### ISSUE TITLE
モデルを作成する

### ISSUE THREAD

**Issue by iQeda** [taichi-kobaya/LaravelPortfolio#8]
マイグレーションでテーブルを作成したら、モデルファイルが利用可能になります。
モデルファイルを作成してください。

**Comment by taichi-kobaya** [comment]
https://www.youtube.com/watch?v=DzsYsgRuwZE&t=10s
上記youtube動画を参考に、以下手順でモデル作成しました。

- php artisan make:model Models/Contact コマンド実行　→　既にModelsフォルダがあり、Modelsフォルダの中にさらにModelsフォルダが作られてしまいました
- エクスプローラでModelsフォルダの中身のContact.phpを切り取り、app/Modelsの配下に配置　→　app/Models/Modelsフォルダを削除
- Contact class編集

**Comment by iQeda** [comment]
いえ、`php artisan make:model Models/Contact` コマンド自体が `Models/Models/Contact.php` を生成するという意味です。
`php artisan make:model Contact` であれば `Models/Contact.php` が生成されます。

**Comment by iQeda** [comment]
PR コメントしました！
